### Python NumPy [Basics and Exercises]
##### https://www.w3resource.com/python-exercises/numpy/index.php

### Basics

In [1]:
!pip install numpy

In [2]:
import numpy as np

#### NumPy Arrays

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a = np.random.random((2,4))
print(a)

[[0.68794231 0.11850179 0.14286977 0.14584119]
 [0.41680772 0.34578551 0.88655054 0.29864864]]


In [72]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [73]:
np.full((2,3), 101)

array([[101, 101, 101],
       [101, 101, 101]])

In [77]:
np.full_like(a, 0, dtype="int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
np.full(a.shape, 11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [80]:
np.random.rand(2,2)

array([[0.35062453, 0.17514571],
       [0.20686535, 0.01125379]])

In [84]:
np.random.randint(90, size=(2,4))

array([[83,  2, 31, 63],
       [29, 20, 68, 46]])

In [93]:
# problem: 
# create following array:
# [1,1,1,1,1]
# [1,0,0,0,1]
# [1,0,9,0,1]
# [1,0,0,0,1]
# [1,1,1,1,1]

x = np.full((5,5), 1, dtype="int32")
x[1:4, 1:4] = 0
x[2, 2] = 9
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


###### Be careful when copying np arrays

In [98]:
y = np.array([1,2,3,4,5])
z = y
print(f"x= {y}, y={z}")
z[2] = 10
print(f"x= {y}, y={z}")

x= [1 2 3 4 5], y=[1 2 3 4 5]
x= [ 1  2 10  4  5], y=[ 1  2 10  4  5]


In [99]:
# instead do following

In [100]:
z = y.copy()

print(f"x= {y}, y={z}")
z[2] = 40
print(f"x= {y}, y={z}")

x= [ 1  2 10  4  5], y=[ 1  2 10  4  5]
x= [ 1  2 10  4  5], y=[ 1  2 40  4  5]


##### Array properties

In [61]:
a = np.random.random((3,5))
print(a)

[[0.78297542 0.72327489 0.49900757 0.34580643 0.15338873]
 [0.5708914  0.97450302 0.02952681 0.09425816 0.49760734]
 [0.69030382 0.61865428 0.64677257 0.45163474 0.00663095]]


In [62]:
print(f"Dimensions: {a.ndim}")
print(f"Shape: {a.shape}")
print(f"Size (Total Elements): {a.size}")
print(f"Data type: {a.dtype}")

Dimensions: 2
Shape: (3, 5)
Size (Total Elements): 15
Data type: float64


##### Accessing elements of array

In [63]:
# instead of a[r][c]
# do a[r, c]

a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [64]:
a[1, 3]

9

In [65]:
a[-1, -3]

13

In [66]:
a[:1]

array([[1, 2, 3, 4, 5]])

In [67]:
a[1,:] # access specific column

array([ 6,  7,  8,  9, 10])

In [68]:
a[:, 2] # access specific column

array([ 3,  8, 13])

##### Mathematics

In [101]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [102]:
a + 2

array([3, 4, 5, 6, 7])

In [103]:
a-2

array([-1,  0,  1,  2,  3])

In [104]:
a*2

array([ 2,  4,  6,  8, 10])

In [105]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [106]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [107]:
a += 2
a

array([3, 4, 5, 6, 7])

In [108]:
a**2

array([ 9, 16, 25, 36, 49])

In [110]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

##### Linear Algebra

In [113]:
a = np.ones((2,3))
b = np.full((3,2), 2)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [115]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [127]:
# determinant

a = np.array([[1,2,3], [11,1212,2122], [7,8,9]])
a

array([[   1,    2,    3],
       [  11, 1212, 2122],
       [   7,    8,    9]])

In [128]:
int(np.linalg.det(a))

-1746

##### Statictics

In [131]:
a = np.array([[21,2,14,35,12,32], [231,124,1,51,5,235]])
a

array([[ 21,   2,  14,  35,  12,  32],
       [231, 124,   1,  51,   5, 235]])

In [132]:
np.min(a)

1

In [133]:
np.max(a)

235

In [135]:
np.mean(a)

63.583333333333336

In [137]:
np.min(a, axis=1)

array([2, 1])

In [139]:
np.max(a, axis=1)

array([ 35, 235])

In [141]:
np.sum(a, axis=0)

array([252, 126,  15,  86,  17, 267])

In [142]:
np.sum(a, axis=1)

array([116, 647])

##### Re-organizing array

In [145]:
before = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(before)

after = before.reshape((5,2))
print(after)
print(after.reshape((1,10)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [146]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [148]:
np.vstack((a,b,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [150]:
np.hstack((a,a,b))

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8])

##### Load data from file

In [153]:
file_data = np.genfromtxt("21_data.txt", delimiter=",")
print(file_data)
print(file_data.astype("int32"))
file_data = file_data.astype("int32")
print(file_data)


[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


##### Boolean Masking and Advanced Indexing

In [156]:
file_data > 12

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [157]:
file_data[file_data > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [166]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [167]:
# problem:
file_data = np.genfromtxt("21_data.txt", delimiter=",")
print(file_data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]


In [170]:
# get [11,12] through indexing
#     [16,17] 

file_data[2:4, :2]

array([[11., 12.],
       [16., 17.]])

In [178]:
# get [4,5] through indexing
#     [24,25] 
#     [29,30] 

file_data[[0,-2,-1], 3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])

### 1 Basic Operations and Arrays Exercises

#### Numpy Basics Exercises

In [179]:
import numpy as np

In [180]:
np.__version__

'1.26.4'

In [181]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/KaranJJoshi/anaconda3/Library/include
    lib directory: C:/Users/KaranJJoshi/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  hos

#1. Write a NumPy program to swap rows and columns of a given array in reverse order.

In [183]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
a[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [196]:
# Wrong
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

#2. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [202]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [203]:
b[:, [0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [217]:
new_array = b.copy()
new_array[:, [0]], new_array[:, [-1]] = new_array[:, [-1]], new_array[:, [0]]
new_array[:, [1]], new_array[:, [-2]] = new_array[:, [-2]], new_array[:, [1]]
new_array

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

#### Numpy Basics Exercises

#1. Write a NumPy program to extract all the rows to compute the student weight from a given array (student information) where a specific column starts with a given character.

In [257]:
a = np.array(
[['01','V','Debby Pramod','30.21'],
['02','V','Artemiy Ellie','29.32'],
['03','V','Baptist Kamal','31.0'],
['04','V','Lavanya Davide','30.22'],
['05','V','Fulton Antwan','30.21'],
['06','V','Euanthe Sandeep','31.0'],
['07','V','Endzela Sanda','32.0'],
['08','V','Victoire Waman','29.21'],
['09','V','Briar Nur','30.0'],
['10','V','Rose Lykos','32.0']])
a

array([['01', 'V', 'Debby Pramod', '30.21'],
       ['02', 'V', 'Artemiy Ellie', '29.32'],
       ['03', 'V', 'Baptist Kamal', '31.0'],
       ['04', 'V', 'Lavanya Davide', '30.22'],
       ['05', 'V', 'Fulton Antwan', '30.21'],
       ['06', 'V', 'Euanthe Sandeep', '31.0'],
       ['07', 'V', 'Endzela Sanda', '32.0'],
       ['08', 'V', 'Victoire Waman', '29.21'],
       ['09', 'V', 'Briar Nur', '30.0'],
       ['10', 'V', 'Rose Lykos', '32.0']], dtype='<U15')

In [258]:
res = a[np.char.startswith(a[:, 2], "E")]
res

array([['06', 'V', 'Euanthe Sandeep', '31.0'],
       ['07', 'V', 'Endzela Sanda', '32.0']], dtype='<U15')

In [264]:
answer = res[:, -1].astype("float").sum()
answer

63.0

#2. Write a NumPy program to calculate the arithmetic mean of the corresponding elements of two given arrays of the same size.

In [267]:
a = np.array([[2,5,2],[1,5,5]])
b = np.array([[5,3,4],[3,2,5]])

In [271]:
c = np.array((a+b)/2)
print(c)

[[3.5 4.  3. ]
 [2.  3.5 5. ]]


### 2 NumPy Math, Linear Algebraa and Statistics Exercises

#### Maths Exercises

#1. Write a NumPy program to find the roots of the following polynomials.

a) x2 - 4x + 7.
b) x4 - 11x3 + 9x2 + 11x - 10

In [278]:
np.roots([1,-4,7])

array([2.+1.73205081j, 2.-1.73205081j])

In [280]:
np.roots([1,-11,9,11,-10])

array([10.        , -1.        ,  0.99999998,  1.00000002])

#2. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.
Sample output

In [281]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,1], [1,2]])

print(a**b)

[[ 1  2]
 [ 3 16]]


#3. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array

Original array: <br>
[ 1 3 5 0 -1 -7 0 5] <br>
Element-wise indication of the sign for all elements of the said array: <br>
[ 1 1 1 0 -1 -1 0 1]

In [286]:
a = np.array([1,3,5,0,-1,-7,0,5])
a

array([ 1,  3,  5,  0, -1, -7,  0,  5])

In [292]:
a[a > 0] = 1
a[a < 0 ] = -1
print(f"Final Result: \n{a}")

Final Result: 
[ 1  1  1  0 -1 -1  0  1]


#### Linear Algebra Exercises

#1. Write a NumPy program to compute the sum of the diagonal element of a given array 

In [293]:
m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [306]:
print(f"Sum of diagonal elements : {sum(m1[[0,1,2], [0,1,2]])}")
# or we can do following:
print(f"Sum of diagonal elements : {np.trace(m1)}")

Sum of diagonal elements : 15
Sum of diagonal elements : 15


#2. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

In [307]:
m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

U, s, v = np.linalg.svd(m2)
print(f"m2 = Usv^T\n")
print(f"U :\n{U}")
print(f"s :\n{s}")
print(f"v :\n{v}")

m2 = Usv^T

U :
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
s :
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
v :
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


#### Statistics Exercises

#1. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

Original array: <br>
[0, 1, 6, 1, 4, 1, 2, 2, 7] <br>
Number of occurrences of each value in array: <br>
[1 3 2 0 1 0 1 1] <br>

In [309]:
c = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
c

array([0, 1, 6, 1, 4, 1, 2, 2, 7])

In [313]:
print(f"Freq: {np.bincount(c)}")

Freq: [1 3 2 0 1 0 1 1]


### 3 Numpy Ranodm Exercises

#1. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).

In [317]:
mat = np.random.randint(0, 256, (300,400,5))
mat

array([[[250,  18, 214,  76,   0],
        [  8, 211, 164, 247,  92],
        [ 30,  47, 125, 107,  21],
        ...,
        [195,  26, 168, 173, 152],
        [ 53, 133,  69, 177,  38],
        [ 13, 139, 133,  16,  26]],

       [[154, 243, 216, 186, 217],
        [ 34,  38,  12, 249,  29],
        [212, 127,  43, 253, 196],
        ...,
        [160, 192, 194, 241,  64],
        [ 21, 172,  72,   9, 161],
        [240, 116,  28, 233,  14]],

       [[ 99, 104, 158, 206, 169],
        [185,  48, 168,  98,  61],
        [ 31,  60,   8, 229, 164],
        ...,
        [119, 164,  34, 225,  68],
        [251,  19, 199, 131,  34],
        [145, 112,   8,   7,  11]],

       ...,

       [[106,  82,  44, 154, 169],
        [ 45, 210, 163, 237, 117],
        [196,  38, 143,  35, 167],
        ...,
        [116, 103,  24, 220, 239],
        [ 83, 171, 138, 159, 153],
        [231, 174, 227,  39, 203]],

       [[ 17,  69,  30, 134,  86],
        [ 54, 144, 184, 110, 249],
        [179,  33

#2. Write a NumPy program to find the most frequent value in an array.

In [348]:
x = np.random.randint(0, 11, 15)
x

array([3, 3, 7, 3, 4, 6, 3, 3, 7, 7, 2, 8, 0, 0, 9])

In [349]:
from collections import Counter
Counter(x).most_common()

[(3, 5), (7, 3), (0, 2), (4, 1), (6, 1), (2, 1), (8, 1), (9, 1)]

In [350]:
np.bincount(x).argmax()

3

### 4 NumPy Searching, Sorting and Indexing

#### Searching and Sorting Exercises

#1. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

<code>Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 ) (b'Nail', 6, 52.5 )]
</code>

In [8]:
dt = np.dtype([('name', 'U10'), ('class', 'i4'), ('height', 'f4')])

students = np.array([[('James', 5, 48.5 ), ('Nail', 6, 52.5 ), ('Paul', 5, 42.1 ), ('Pit', 5, 40.11)]], dtype=dt)

In [10]:
print(students)

[[('James', 5, 48.5 ) ('Nail', 6, 52.5 ) ('Paul', 5, 42.1 )
  ('Pit', 5, 40.11)]]


In [17]:
print(np.sort(students, order='height'))

[[('Pit', 5, 40.11) ('Paul', 5, 42.1 ) ('James', 5, 48.5 )
  ('Nail', 6, 52.5 )]]


#2. Write a NumPy program to get the indices of the sorted elements of a given array.

In [18]:
a = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
a

array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [21]:
sorted_indices = np.argsort(a)
print(f"Indices of sorted elements : \n{sorted_indices}")

Indices of sorted elements : 
[0 3 4 6 1 5 2]


In [22]:
a[sorted_indices]

array([1023, 1671, 1682, 4532, 5202, 5241, 6230])

#2. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

In [32]:
arr = np.random.randint(11, 31, 10)
arr

array([29, 25, 16, 28, 13, 15, 13, 21, 23, 18])

In [33]:
part = np.partition(arr, 4)
part

array([15, 13, 16, 13, 18, 25, 28, 21, 23, 29])

#### Advanced Indexing Exercises

#1. Write a NumPy program that creates a 5D NumPy array. Use boolean indexing to select elements along specific dimensions based on conditions applied to other dimensions.

In [34]:
mat = np.random.randint(11, 101, (2,3,4,2,3))
mat

array([[[[[ 47,  60,  76],
          [ 28,  79,  74]],

         [[ 73,  64,  65],
          [ 42,  38,  47]],

         [[ 81,  37,  94],
          [ 86,  27,  47]],

         [[ 85,  31,  90],
          [ 97,  32,  79]]],


        [[[ 91,  28,  44],
          [ 43,  89,  38]],

         [[ 75,  36,  13],
          [ 84,  40,  52]],

         [[ 72,  22,  64],
          [ 54,  79,  57]],

         [[ 59,  38,  93],
          [ 18,  94, 100]]],


        [[[ 21,  31,  65],
          [ 84,  67,  50]],

         [[ 22,  85,  79],
          [100,  61,  15]],

         [[ 28,  15,  58],
          [ 81,  68,  96]],

         [[ 92,  23,  98],
          [ 88,  75,  84]]]],



       [[[[ 16,  63,  78],
          [ 27, 100,  86]],

         [[ 61,  28,  32],
          [ 63,  23,  19]],

         [[ 40,  24,  33],
          [ 48,  36,  79]],

         [[ 27,  14,  18],
          [ 65,  47,  19]]],


        [[[ 55,  95,  40],
          [ 67,  13,  14]],

         [[ 96,  70,  22],
          [

In [35]:
mat>50

array([[[[[False,  True,  True],
          [False,  True,  True]],

         [[ True,  True,  True],
          [False, False, False]],

         [[ True, False,  True],
          [ True, False, False]],

         [[ True, False,  True],
          [ True, False,  True]]],


        [[[ True, False, False],
          [False,  True, False]],

         [[ True, False, False],
          [ True, False,  True]],

         [[ True, False,  True],
          [ True,  True,  True]],

         [[ True, False,  True],
          [False,  True,  True]]],


        [[[False, False,  True],
          [ True,  True, False]],

         [[False,  True,  True],
          [ True,  True, False]],

         [[False, False,  True],
          [ True,  True,  True]],

         [[ True, False,  True],
          [ True,  True,  True]]]],



       [[[[False,  True,  True],
          [False,  True,  True]],

         [[ True, False, False],
          [ True, False, False]],

         [[False, False, False],
       

In [37]:
print(mat[mat>50])

[ 60  76  79  74  73  64  65  81  94  86  85  90  97  79  91  89  75  84
  52  72  64  54  79  57  59  93  94 100  65  84  67  85  79 100  61  58
  81  68  96  92  98  88  75  84  63  78 100  86  61  63  79  65  55  95
  67  96  70  77  58  66  85  90  54  79  68  72  58  52  90  92  66  62
  71  89  51  88  55  89  61  93  74  71]


### 5 NumPy Datetime and Strings Operations 

#### Datetime Operations Exercises

#1.  Write a NumPy program to display all the dates for the month of March, 2017.
Expected Output:

In [39]:
dates = np.arange("2017-03-01", "2017-04-01", dtype="datetime64")
print(f"Dates of March of 2017: \n{dates}")

Dates of March of 2017: 
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


<code>
#2. Write a NumPy program to find the number of weekdays in March 2017.
    Note: "busday" default of Monday through Friday being valid days.
</code>

In [46]:
print(f"Business Days[Week Days] of March 20127: {np.busday_count("2017-03", "2017-04")}")

Business Days[Week Days] of March 20127: 23


#3. Write a NumPy program to find the first Monday in May 2017.

In [52]:
print(f"First Monday of May 2017: \n{np.busday_offset("2025-05", 0, roll="forward", weekmask="Sun")}")

First Monday of May 2017: 
2025-05-04


#### String Operations Exercises

#1. Write a NumPy program to split a given text into lines and split the single line into array values.

<code>
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""
</code>

In [68]:
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

students = student.split("\n")

students = [student.split("\t") for student in students]

In [71]:
students = np.array(students)

In [72]:
students

array([['01', 'V', 'Debby Pramod'],
       ['02', 'V', 'Artemiy Ellie'],
       ['03', 'V', 'Baptist Kamal'],
       ['04', 'V', 'Lavanya Davide'],
       ['05', 'V', 'Fulton Antwan'],
       ['06', 'V', 'Euanthe Sandeep'],
       ['07', 'V', 'Endzela Sanda'],
       ['08', 'V', 'Victoire Waman'],
       ['09', 'V', 'Briar Nur'],
       ['10', 'V', 'Rose Lykos']], dtype='<U15')

#2. Write a NumPy program to add two zeros to the beginning of each element of a given array of string values.

In [103]:
arr = np.array(['1.12','2.23','3.71','4.23','5.11'], dtype=str)
               
print(f"After adding two zeros before strings arr: \n{np.char.add('00', arr)}")
print(f"After adding two zeros before strings arr: \n{np.char.rjust(arr, 6, fillchar='0')}")

After adding two zeros before strings arr: 
['001.12' '002.23' '003.71' '004.23' '005.11']
After adding two zeros before strings arr: 
['001.12' '002.23' '003.71' '004.23' '005.11']


### 6 NumPy Broadcasting and Memory Layout

#### Broadcasting Exercises

#1. Write a NumPy program that Multiplies each column of a 2D array x of shape (7, 3) by a 1D array y of shape (7,) using broadcasting.

In [119]:
a1 = np.random.randint(11, 100, (7,3))
a2 = np.random.randint(11, 100, 7)

In [120]:
print(a1)
print(a2)

[[20 59 52]
 [65 52 98]
 [71 55 11]
 [66 28 15]
 [56 71 60]
 [63 47 57]
 [74 37 89]]
[12 11 32 72 48 59 25]


In [125]:
print(f"Mul of a1's each column and a2: ")
answer = a1.reshape(3,7)*a2
print(answer.reshape(7,3))

Mul of a1's each column and a2: 
[[ 240  649 1664]
 [4680 2496 5782]
 [1775  660  121]
 [2112 2016  720]
 [3304 1775  720]
 [ 693 1504 4104]
 [3552 2183 2225]]


In [126]:
# real answer
print(a1*a2[:, np.newaxis])

[[ 240  708  624]
 [ 715  572 1078]
 [2272 1760  352]
 [4752 2016 1080]
 [2688 3408 2880]
 [3717 2773 3363]
 [1850  925 2225]]


#2. Write a NumPy program that creates a 2D array x of shape (4, 4) and a scalar y. Perform element-wise multiplication of a and b using broadcasting.

In [129]:
a = np.random.randint(11, 31, (4, 4))
b = 7
print(a)
print(b)
print(a*b)

[[13 23 21 29]
 [16 25 17 25]
 [17 16 22 24]
 [23 23 23 28]]
7
[[ 91 161 147 203]
 [112 175 119 175]
 [119 112 154 168]
 [161 161 161 196]]


#3. Given two arrays, x of shape (2, 1, 3) and y of shape (1, 4, 1), use broadcasting write a NumPy program to obtain a result of shape (2, 4, 3) through element-wise addition.

In [130]:
x = np.array([[[1, 2, 3]], 
              [[4, 5, 6]]])

y = np.array([[[ 7], [ 8], [ 9], [10]]])

print(x*y)

[[[ 7 14 21]
  [ 8 16 24]
  [ 9 18 27]
  [10 20 30]]

 [[28 35 42]
  [32 40 48]
  [36 45 54]
  [40 50 60]]]


#### Memory Layout Exercises

#1. Write a NumPy program that creates a 1D array of 20 elements and use reshape() to create a (4, 5) matrix. Slice a (2, 3) sub-matrix and print its strides.

In [133]:
arr = np.random.randint(11, 21, 20).reshape(4,5)
print(arr)
print(arr.strides)

[[12 19 19 15 15]
 [12 13 20 19 14]
 [11 19 20 11 13]
 [20 19 14 13 12]]
(20, 4)


In [134]:
sliced = arr[1:3, 1:4]
print(sliced)
print(sliced.strides)

[[13 20 19]
 [19 20 11]]
(20, 4)


### 7 NumPy Performance Optimization and Interoperability

#### Performance Optimization Exercises

#1. Write a NumPy program that creates a large 1D array and write a function to calculate the sum of its elements using a for loop. Then, optimize it using NumPy's built-in functions.

In [140]:
import time

arr = np.random.randint(11, 100, 500000)

total = 0
start = time.time()
for item in arr:
    total += item
end = time.time()
print(f"Using loop : {end-start} seconds")
print(f"Total : {total}")

start = time.time()
total = np.sum(arr)
end = time.time()
print(f"Using np : {end-start} seconds")
print(f"Total : {total}")

Using loop : 0.28883910179138184 seconds
Total : 27480659
Using np : 0.000995635986328125 seconds
Total : 27480659


#### Ineropearability Exercises

#1. Write a NumPy program to combine a NumPy array and a Pandas DataFrame into a single DataFrame and print it.

In [141]:
import pandas as pd
import numpy as np

In [142]:
arr = np.array([10, 20, 30])

data = {
    "A": [1, 2, 3],
    "B": [11, 22, 33]
}

df = pd.DataFrame(data)

print(arr)
print(df)

[10 20 30]
   A   B
0  1  11
1  2  22
2  3  33


In [143]:
np_df = pd.DataFrame(arr, columns=["c"])
print(np_df)

    c
0  10
1  20
2  30


In [149]:
combined = pd.concat([df, np_df], axis=1)
print("Combined DataFrame : ")
print(combined)

Combined DataFrame : 
   A   B   c
0  1  11  10
1  2  22  20
2  3  33  30


### 8 NumPy I/O operations

#### I/O operations exercises

#1. Write a NumPy program that saves multiple NumPy arrays to a single binary file using np.savez and then loads them back using np.load.

In [152]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a3 = np.array([[1,2,3],[4,5,6],[8,9,10]])

np.savez("21_multiple_array.npz", array1=a1, array2=a2, array3=a3)

In [156]:
multiple_array_data = np.load("21_multiple_array.npz")

print(multiple_array_data['array1'])
print(multiple_array_data['array2'])
print(multiple_array_data['array3'])

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


#2. Write a NumPy array to a CSV file with a custom delimiter and then read it back into a NumPy array using the same delimiter.

In [166]:
np.random.seed(32)
arr = np.random.randint(11, 100, (5,10))

csv_file = "21_np_to_csv.csv"

np.savetxt(csv_file, arr, delimiter="|", fmt='%d')

data_from_csv = np.loadtxt(csv_file, delimiter="|")

data_from_csv

array([[98., 54., 16., 65., 73., 99., 30., 82., 14., 20.],
       [15., 22., 92., 14., 76., 45., 46., 35., 53., 93.],
       [21., 95., 61., 68., 80., 49., 88., 22., 73., 22.],
       [40., 63., 75., 22., 17., 79., 73., 41., 91., 94.],
       [61., 85., 46., 72., 61., 56., 35., 22., 58., 54.]])

### 9 NumPy U Functions and Masked Arrays

#### U Functions Exercises

#1. Write a NumPy program that creates a custom ufunc to operate on complex numbers in a NumPy array.

In [168]:
def add_complex(z):
    return z.real + z.imag

ufunc_add_complex = np.frompyfunc(add_complex, 1, 1)

arr = np.array([1+2j, 1-2j, 3+4j])

print(f"Sum of complex numbers array: \n{ufunc_add_complex(arr)}")

Sum of complex numbers array: 
[3.0 -1.0 7.0]


#2. Write a NumPy program that creates an array with NaN values and uses np.nan_to_num to replace NaN with a specified number.

In [177]:
arr = np.full((2,3), np.nan)

In [178]:
arr

array([[nan, nan, nan],
       [nan, nan, nan]])

In [179]:
print("NaN converted to 9 : ")
print(np.nan_to_num(arr, nan=0.0))

NaN converted to 9 : 
[[0. 0. 0.]
 [0. 0. 0.]]


#3. Write a NumPy program that creates a custom ufunc that computes x^2 + 2x + 1 for each element in a NumPy array.

In [182]:
def compute(num):
    return (num**2) + (num*2) + 1

ufunc_compute = np.frompyfunc(compute, 1, 1)

arr = np.random.randint(1, 10, (2,4))
print(arr)
print(f"Computataion of equation of each element : ")
print(ufunc_compute(arr))

[[6 2 1 4]
 [2 8 9 7]]
Computataion of equation of each element : 
[[49 9 4 25]
 [9 81 100 64]]


#### Masked Arrays Exercises

#1. Write a NumPy program that creates a masked array and applies a mathematical function (e.g., sin, cos) only to the unmasked elements.

In [184]:
import numpy.ma as ma

In [185]:
arr = np.array([1,2,3,np.nan,4,5,6,np.inf,9,10])

In [186]:
arr

array([ 1.,  2.,  3., nan,  4.,  5.,  6., inf,  9., 10.])

In [189]:
masked_arr = ma.masked_invalid(arr)
print(masked_arr.data)
print(masked_arr.mask)

[ 1.  2.  3. nan  4.  5.  6. inf  9. 10.]
[False False False  True False False False  True False False]


In [194]:
print(ma.cos(masked_arr).data)
print(ma.cos(masked_arr).mask)

[ 0.54030231 -0.41614684 -0.9899925          nan -0.65364362  0.28366219
  0.96017029         inf -0.91113026 -0.83907153]
[False False False  True False False False  True False False]


In [192]:
ma.mean(ma.sin(masked_arr))

-0.02939455926552003

#2. Write a NumPy program that creates a masked array and changes the mask to include additional elements.

In [222]:
arr = np.random.randint(11, 100, (5, 5))
arr

array([[90, 89, 21, 84, 21],
       [30, 60, 90, 48, 47],
       [33, 88, 73, 58, 66],
       [64, 72, 84, 41, 61],
       [97, 49, 50, 15, 11]])

In [224]:
less_than_20 = arr < 20
masked_arr = ma.masked_array(arr, mask=less_than_20) 

In [225]:
masked_arr

masked_array(
  data=[[90, 89, 21, 84, 21],
        [30, 60, 90, 48, 47],
        [33, 88, 73, 58, 66],
        [64, 72, 84, 41, 61],
        [97, 49, 50, --, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False,  True,  True]],
  fill_value=999999)

In [230]:
additional_condition = arr > 80
masked_arr.mask = less_than_20 | additional_condition
masked_arr

masked_array(
  data=[[--, --, 21, --, 21],
        [30, 60, --, 48, 47],
        [33, --, 73, 58, 66],
        [64, 72, --, 41, 61],
        [--, 49, 50, --, --]],
  mask=[[ True,  True, False,  True, False],
        [False, False,  True, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [ True, False, False,  True,  True]],
  fill_value=999999)

#3. Write a NumPy program to create a masked array and convert it back to a regular NumPy array, replacing the masked values with NaN.

In [271]:
masked_arr = ma.masked_less(np.round(np.random.rand(20)*3, 2), 1.2)

In [272]:
masked_arr

masked_array(data=[2.12, --, 2.05, --, 2.56, --, --, --, 1.52, 1.27, --,
                   1.89, --, --, 2.13, --, 2.13, 1.56, --, 2.06],
             mask=[False,  True, False,  True, False,  True,  True,  True,
                   False, False,  True, False,  True,  True, False,  True,
                   False, False,  True, False],
       fill_value=1e+20)

In [273]:
regular_arr = masked_arr.filled(np.nan)
regular_arr

array([2.12,  nan, 2.05,  nan, 2.56,  nan,  nan,  nan, 1.52, 1.27,  nan,
       1.89,  nan,  nan, 2.13,  nan, 2.13, 1.56,  nan, 2.06])

### 10 NumPy Structured Arrays and SciPy Integration

#### Structured Arrays Exercises

#1. Write a NumPy program that adds a new record to the structured array created array with fields for 'name' (string), 'age' (integer), and 'height' (float) with the fields: 'name': ' Nela Suna ', 'age': 25, 'height': 5.9.

In [301]:
dt = np.dtype([("name", "U15"), ("age", "i4"), ("height", "f4")])

In [302]:
person_details = np.array([("Karan", 21, 5.4), ("Deep", 21, 5.6), ("Aditya", 23, 5.9)], dtype=dt)

In [303]:
person_details

array([('Karan', 21, 5.4), ('Deep', 21, 5.6), ('Aditya', 23, 5.9)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('height', '<f4')])

In [304]:
updated_person_details = np.append(person_details, np.array([("Nela Suna", 25, 5.9)], dtype=dt))

In [305]:
updated_person_details

array([('Karan', 21, 5.4), ('Deep', 21, 5.6), ('Aditya', 23, 5.9),
       ('Nela Suna', 25, 5.9)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('height', '<f4')])

#2. Write a NumPy program that uses advanced indexing to select records from the structured array created with fields for 'name' (string), 'age' (integer), and 'height' (float) where both 'age' is greater than 25 and 'height' is less than 6.0.

In [324]:
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]

structured_array = np.array([
    ('Lehi Piero', 25, 5.5),
    ('Albin Achan', 30, 5.8),
    ('Zerach Hava', 35, 6.1),
    ('Edmund Tereza', 40, 5.9),
    ('Laura Felinus', 28, 5.7)
], dtype=dtype)    

print(f"Person with age > 25 and height < 6.0: ")
print(structured_array[(structured_array["age"] > 25) & (structured_array["height"] < 6.0)])

Person with age > 25 and height < 6.0: 
[('Albin Acha', 30, 5.8) ('Edmund Ter', 40, 5.9) ('Laura Feli', 28, 5.7)]


#### SciPy Integration Exercises

#1. Write a NumPy program to generate synthetic data using NumPy and apply SciPy's stats module to perform various statistical tests (t-test).

In [340]:
from scipy import stats

In [341]:
np.random.seed(28)

In [342]:
a1 = np.random.normal(loc=30, scale=6, size=100)
a2 = np.random.normal(loc=32, scale=6, size=100)

In [343]:
a1

array([32.67799427, 40.01472031, 28.41432023, 24.19299042, 30.35513055,
       39.08771994, 32.02122266, 28.18578779, 24.96814918, 26.89361249,
       31.52104718, 15.09177608, 26.09148079, 19.34718509, 31.40571496,
       37.43639915, 26.09799435, 28.40271044, 26.76768138, 32.52444317,
       29.42828204, 25.38074341, 28.8976528 , 31.06085368, 34.42233714,
       34.16317585, 25.10681802, 32.32608273, 30.63922203, 28.11253846,
       25.80172287, 30.31792968, 35.60464706, 38.75923281, 20.5267373 ,
       35.7135986 , 26.38524335, 32.76866954, 29.97624512, 34.66408816,
       27.04132316, 33.65118519, 31.8854051 , 25.73217741, 36.03177627,
       31.26755381, 24.76110697, 35.90494241, 29.57878097, 40.6723321 ,
       29.74406345, 30.27888093, 36.00539741, 37.92627994, 37.02657777,
       25.28883098, 33.02229492, 16.74187843, 31.33103421, 16.7732831 ,
       34.00902976, 27.28391509, 21.08242522, 35.620681  , 31.88410154,
       31.31216527, 33.94912851, 32.63689261, 31.53932492, 31.34

In [344]:
a2

array([32.52378208, 32.53700797, 40.49552254, 26.9503091 , 35.67437301,
       34.52555202, 35.88304449, 31.62510384, 31.76378438, 45.6366015 ,
       35.52932273, 27.77706185, 24.61886736, 28.72973563, 25.69987151,
       28.19542431, 25.76604674, 30.45855691, 34.92388914, 38.69011213,
       37.1951627 , 36.61829427, 34.25852797, 39.99757917, 31.29113288,
       29.93854201, 37.12828878, 30.24016409, 30.5198196 , 30.15782611,
       32.14179897, 35.5486779 , 22.39621635, 31.83386714, 29.63754842,
       28.86240148, 37.41004584, 33.20349208, 41.15338226, 31.91160518,
       33.72533273, 26.24145009, 32.11308242, 37.31823138, 42.59367429,
       30.13171351, 31.50700304, 20.87646661, 30.71147648, 33.54626216,
       30.38144657, 45.18674703, 33.81285128, 40.57717492, 26.84169382,
       28.52269224, 45.07371563, 32.73100943, 27.04883543, 41.00180868,
       26.4258312 , 26.25432374, 32.80791544, 28.27727943, 24.08938514,
       32.46673771, 23.84096839, 31.04777232, 26.3088017 , 35.02

In [345]:
stats.ttest_ind(a1, a2)

TtestResult(statistic=-2.584374565328871, pvalue=0.010474908594238979, df=198.0)

### 11 NumPy Advanced Topics and Matery

#### NumPy Advanced Exercises

#1. Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

In [350]:
from scipy.spatial import distance

arr = np.random.randint(11, 100, (3, 3))
arr

array([[21, 41, 39],
       [49, 13, 42],
       [95, 63, 14]])

In [351]:
dis = distance.cdist(arr, arr, "euclidean")

In [352]:
dis

array([[ 0.        , 39.7114593 , 81.14801291],
       [39.7114593 ,  0.        , 73.48469228],
       [81.14801291, 73.48469228,  0.        ]])