### Python NumPy [Basics and Exercises]
##### https://www.w3resource.com/python-exercises/numpy/index.php

### Basics

In [1]:
!pip install numpy

In [2]:
import numpy as np

#### NumPy Arrays

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a = np.random.random((2,4))
print(a)

[[0.68794231 0.11850179 0.14286977 0.14584119]
 [0.41680772 0.34578551 0.88655054 0.29864864]]


In [72]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [73]:
np.full((2,3), 101)

array([[101, 101, 101],
       [101, 101, 101]])

In [77]:
np.full_like(a, 0, dtype="int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
np.full(a.shape, 11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [80]:
np.random.rand(2,2)

array([[0.35062453, 0.17514571],
       [0.20686535, 0.01125379]])

In [84]:
np.random.randint(90, size=(2,4))

array([[83,  2, 31, 63],
       [29, 20, 68, 46]])

In [93]:
# problem: 
# create following array:
# [1,1,1,1,1]
# [1,0,0,0,1]
# [1,0,9,0,1]
# [1,0,0,0,1]
# [1,1,1,1,1]

x = np.full((5,5), 1, dtype="int32")
x[1:4, 1:4] = 0
x[2, 2] = 9
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


###### Be careful when copying np arrays

In [98]:
y = np.array([1,2,3,4,5])
z = y
print(f"x= {y}, y={z}")
z[2] = 10
print(f"x= {y}, y={z}")

x= [1 2 3 4 5], y=[1 2 3 4 5]
x= [ 1  2 10  4  5], y=[ 1  2 10  4  5]


In [99]:
# instead do following

In [100]:
z = y.copy()

print(f"x= {y}, y={z}")
z[2] = 40
print(f"x= {y}, y={z}")

x= [ 1  2 10  4  5], y=[ 1  2 10  4  5]
x= [ 1  2 10  4  5], y=[ 1  2 40  4  5]


##### Array properties

In [61]:
a = np.random.random((3,5))
print(a)

[[0.78297542 0.72327489 0.49900757 0.34580643 0.15338873]
 [0.5708914  0.97450302 0.02952681 0.09425816 0.49760734]
 [0.69030382 0.61865428 0.64677257 0.45163474 0.00663095]]


In [62]:
print(f"Dimensions: {a.ndim}")
print(f"Shape: {a.shape}")
print(f"Size (Total Elements): {a.size}")
print(f"Data type: {a.dtype}")

Dimensions: 2
Shape: (3, 5)
Size (Total Elements): 15
Data type: float64


##### Accessing elements of array

In [63]:
# instead of a[r][c]
# do a[r, c]

a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [64]:
a[1, 3]

9

In [65]:
a[-1, -3]

13

In [66]:
a[:1]

array([[1, 2, 3, 4, 5]])

In [67]:
a[1,:] # access specific column

array([ 6,  7,  8,  9, 10])

In [68]:
a[:, 2] # access specific column

array([ 3,  8, 13])

##### Mathematics

In [101]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [102]:
a + 2

array([3, 4, 5, 6, 7])

In [103]:
a-2

array([-1,  0,  1,  2,  3])

In [104]:
a*2

array([ 2,  4,  6,  8, 10])

In [105]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [106]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [107]:
a += 2
a

array([3, 4, 5, 6, 7])

In [108]:
a**2

array([ 9, 16, 25, 36, 49])

In [110]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

##### Linear Algebra

In [113]:
a = np.ones((2,3))
b = np.full((3,2), 2)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [115]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [127]:
# determinant

a = np.array([[1,2,3], [11,1212,2122], [7,8,9]])
a

array([[   1,    2,    3],
       [  11, 1212, 2122],
       [   7,    8,    9]])

In [128]:
int(np.linalg.det(a))

-1746

##### Statictics

In [131]:
a = np.array([[21,2,14,35,12,32], [231,124,1,51,5,235]])
a

array([[ 21,   2,  14,  35,  12,  32],
       [231, 124,   1,  51,   5, 235]])

In [132]:
np.min(a)

1

In [133]:
np.max(a)

235

In [135]:
np.mean(a)

63.583333333333336

In [137]:
np.min(a, axis=1)

array([2, 1])

In [139]:
np.max(a, axis=1)

array([ 35, 235])

In [141]:
np.sum(a, axis=0)

array([252, 126,  15,  86,  17, 267])

In [142]:
np.sum(a, axis=1)

array([116, 647])

##### Re-organizing array

In [145]:
before = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(before)

after = before.reshape((5,2))
print(after)
print(after.reshape((1,10)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [146]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [148]:
np.vstack((a,b,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [150]:
np.hstack((a,a,b))

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8])

##### Load data from file

In [153]:
file_data = np.genfromtxt("21_data.txt", delimiter=",")
print(file_data)
print(file_data.astype("int32"))
file_data = file_data.astype("int32")
print(file_data)


[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


##### Boolean Masking and Advanced Indexing

In [156]:
file_data > 12

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [157]:
file_data[file_data > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [166]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [167]:
# problem:
file_data = np.genfromtxt("21_data.txt", delimiter=",")
print(file_data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]


In [170]:
# get [11,12] through indexing
#     [16,17] 

file_data[2:4, :2]

array([[11., 12.],
       [16., 17.]])

In [178]:
# get [4,5] through indexing
#     [24,25] 
#     [29,30] 

file_data[[0,-2,-1], 3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])

### 1 Basic Operations and Arrays Exercises

#### Numpy Basics Exercises

In [179]:
import numpy as np

In [180]:
np.__version__

'1.26.4'

In [181]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/KaranJJoshi/anaconda3/Library/include
    lib directory: C:/Users/KaranJJoshi/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  hos

#1. Write a NumPy program to swap rows and columns of a given array in reverse order.

In [183]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
a[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [196]:
# Wrong
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

#2. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [202]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [203]:
b[:, [0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [217]:
new_array = b.copy()
new_array[:, [0]], new_array[:, [-1]] = new_array[:, [-1]], new_array[:, [0]]
new_array[:, [1]], new_array[:, [-2]] = new_array[:, [-2]], new_array[:, [1]]
new_array

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

#### Numpy Basics Exercises

#1. Write a NumPy program to extract all the rows to compute the student weight from a given array (student information) where a specific column starts with a given character.

In [257]:
a = np.array(
[['01','V','Debby Pramod','30.21'],
['02','V','Artemiy Ellie','29.32'],
['03','V','Baptist Kamal','31.0'],
['04','V','Lavanya Davide','30.22'],
['05','V','Fulton Antwan','30.21'],
['06','V','Euanthe Sandeep','31.0'],
['07','V','Endzela Sanda','32.0'],
['08','V','Victoire Waman','29.21'],
['09','V','Briar Nur','30.0'],
['10','V','Rose Lykos','32.0']])
a

array([['01', 'V', 'Debby Pramod', '30.21'],
       ['02', 'V', 'Artemiy Ellie', '29.32'],
       ['03', 'V', 'Baptist Kamal', '31.0'],
       ['04', 'V', 'Lavanya Davide', '30.22'],
       ['05', 'V', 'Fulton Antwan', '30.21'],
       ['06', 'V', 'Euanthe Sandeep', '31.0'],
       ['07', 'V', 'Endzela Sanda', '32.0'],
       ['08', 'V', 'Victoire Waman', '29.21'],
       ['09', 'V', 'Briar Nur', '30.0'],
       ['10', 'V', 'Rose Lykos', '32.0']], dtype='<U15')

In [258]:
res = a[np.char.startswith(a[:, 2], "E")]
res

array([['06', 'V', 'Euanthe Sandeep', '31.0'],
       ['07', 'V', 'Endzela Sanda', '32.0']], dtype='<U15')

In [264]:
answer = res[:, -1].astype("float").sum()
answer

63.0

#2. Write a NumPy program to calculate the arithmetic mean of the corresponding elements of two given arrays of the same size.

In [267]:
a = np.array([[2,5,2],[1,5,5]])
b = np.array([[5,3,4],[3,2,5]])

In [271]:
c = np.array((a+b)/2)
print(c)

[[3.5 4.  3. ]
 [2.  3.5 5. ]]


### 2 NumPy Math, Linear Algebraa and Statistics Exercises

#### Maths Exercises

#1. Write a NumPy program to find the roots of the following polynomials.

a) x2 - 4x + 7.
b) x4 - 11x3 + 9x2 + 11x - 10

In [278]:
np.roots([1,-4,7])

array([2.+1.73205081j, 2.-1.73205081j])

In [280]:
np.roots([1,-11,9,11,-10])

array([10.        , -1.        ,  0.99999998,  1.00000002])

#2. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.
Sample output

In [281]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,1], [1,2]])

print(a**b)

[[ 1  2]
 [ 3 16]]


#3. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array

Original array: <br>
[ 1 3 5 0 -1 -7 0 5] <br>
Element-wise indication of the sign for all elements of the said array: <br>
[ 1 1 1 0 -1 -1 0 1]

In [286]:
a = np.array([1,3,5,0,-1,-7,0,5])
a

array([ 1,  3,  5,  0, -1, -7,  0,  5])

In [292]:
a[a > 0] = 1
a[a < 0 ] = -1
print(f"Final Result: \n{a}")

Final Result: 
[ 1  1  1  0 -1 -1  0  1]


#### Linear Algebra Exercises

#1. Write a NumPy program to compute the sum of the diagonal element of a given array 

In [293]:
m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [306]:
print(f"Sum of diagonal elements : {sum(m1[[0,1,2], [0,1,2]])}")
# or we can do following:
print(f"Sum of diagonal elements : {np.trace(m1)}")

Sum of diagonal elements : 15
Sum of diagonal elements : 15


#2. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

In [307]:
m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

U, s, v = np.linalg.svd(m2)
print(f"m2 = Usv^T\n")
print(f"U :\n{U}")
print(f"s :\n{s}")
print(f"v :\n{v}")

m2 = Usv^T

U :
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
s :
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
v :
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


#### Statistics Exercises

#1. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

Original array: <br>
[0, 1, 6, 1, 4, 1, 2, 2, 7] <br>
Number of occurrences of each value in array: <br>
[1 3 2 0 1 0 1 1] <br>

In [309]:
c = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
c

array([0, 1, 6, 1, 4, 1, 2, 2, 7])

In [313]:
print(f"Freq: {np.bincount(c)}")

Freq: [1 3 2 0 1 0 1 1]


### 3 Numpy Ranodm Exercises

#1. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).

In [317]:
mat = np.random.randint(0, 256, (300,400,5))
mat

array([[[250,  18, 214,  76,   0],
        [  8, 211, 164, 247,  92],
        [ 30,  47, 125, 107,  21],
        ...,
        [195,  26, 168, 173, 152],
        [ 53, 133,  69, 177,  38],
        [ 13, 139, 133,  16,  26]],

       [[154, 243, 216, 186, 217],
        [ 34,  38,  12, 249,  29],
        [212, 127,  43, 253, 196],
        ...,
        [160, 192, 194, 241,  64],
        [ 21, 172,  72,   9, 161],
        [240, 116,  28, 233,  14]],

       [[ 99, 104, 158, 206, 169],
        [185,  48, 168,  98,  61],
        [ 31,  60,   8, 229, 164],
        ...,
        [119, 164,  34, 225,  68],
        [251,  19, 199, 131,  34],
        [145, 112,   8,   7,  11]],

       ...,

       [[106,  82,  44, 154, 169],
        [ 45, 210, 163, 237, 117],
        [196,  38, 143,  35, 167],
        ...,
        [116, 103,  24, 220, 239],
        [ 83, 171, 138, 159, 153],
        [231, 174, 227,  39, 203]],

       [[ 17,  69,  30, 134,  86],
        [ 54, 144, 184, 110, 249],
        [179,  33

#2. Write a NumPy program to find the most frequent value in an array.

In [348]:
x = np.random.randint(0, 11, 15)
x

array([3, 3, 7, 3, 4, 6, 3, 3, 7, 7, 2, 8, 0, 0, 9])

In [349]:
from collections import Counter
Counter(x).most_common()

[(3, 5), (7, 3), (0, 2), (4, 1), (6, 1), (2, 1), (8, 1), (9, 1)]

In [350]:
np.bincount(x).argmax()

3